<?php

/**
 * @file
 * Primary module hooks for cron task module.
 */
use Drupal\node\Entity\Node;

function cron_task_mail($key, &$message, $params) {
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
  switch ($key) {
    case 'log':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['text'];
      break;
  }
}

/**
 * Implements hook_cron().
 */
function cron_task_cron() {
  $lastCronRun = \Drupal::state()->get('lastcronrun');
  $currentTimestamp = \Drupal::time()->getCurrentTime();
  if (empty($lastCronRun) || ($currentTimestamp - $lastCronRun) >= 1) {
    $query = \Drupal::entityQuery('node')
      ->condition('type', 'logs')
      ->condition('created', $lastCronRun, '>')
      ->accessCheck(FALSE);

    $nids = $query->execute();

    foreach ($nids as $nid) {
      $node = Node::load($nid);
      $config = \Drupal::config('cron_task.settings');
      $msg = $config->get('subject');
      $txt = $config->get('text');
      // print_r($msg);
      // print_r($txt);
      // exit;
      $tokenService = \Drupal::token();
      $message = $tokenService->replace($msg, ['node' => $node], ['clear' => TRUE]);
      $text = $tokenService->replace($txt, ['node' => $node], ['clear' => TRUE]);
      // print_r($message);
      // print_r($text);
      // exit;

      $params = [
        'subject' => $message,
        'text' => $text,
      ];
      $module = 'cron_task';
      $key = 'log';
      $to = 'shruthirao8042@gmail.com';
      $langcode = \Drupal::currentUser()->getPreferredLangcode();

      $mailManager = \Drupal::service('plugin.manager.mail');
      $send = TRUE;
      $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);

      if ($result['result'] !== TRUE) {
        \Drupal::messenger()->addMessage(t('There was a problem sending the email.'), 'error');
      } else {
        \Drupal::messenger()->addMessage(t('Email has been sent successfully.'), 'status');
      }
    }

    \Drupal::state()->set('lastcronrun', $currentTimestamp);
  }
}


